[package]
name = "onlyprox"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }  

url = "2.5.8"
base64 = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3.33"
sysproxy = "0.3.0"

slint = "1.17.1"

[build-dependencies]
slint-build = "1.17.1"